### ISSUE TITLE
Permissions Issues

### ISSUE THREAD

**Issue by mastermindg** [cpoppema/docker-flexget#11]
I set the PGID and PUID to my user on an NFS mount. Everything on that mount is owned by me and my group. I created the flexget config directory on that mount and dropped the config.yml there. However, when the container starts it creates files owned by root and is unable to open them with my UID/GID.

**Comment by mastermindg** [comment]
I'm launching the container from a bash script:

```
#!/bin/bash
docker stop flexget && docker rm flexget
docker run -d \
    --name=flexget \
    -e PUID=$uid -e PGID=$gid \
    -e WEB_PASSWD=$password \
    -e TORRENT_PLUGIN=transmission \
    -p 5050:5050 \
    -v /shared/flexget:/config \
    -v /shared/downloads:/downloads \
    cpoppema/docker-flexget
```
Here's the response:

```
$ ./start.sh
Error response from daemon: No such container: flexget
5a5646dcccff9c5f86324cec0dafcc2af51eaca1f531194af0b61707a72a0e0c
ken@sharebox:/devel/docker/docker-flexget$ docker logs flexget
*** Running /etc/my_init.d/10_update_flexget.sh...
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages
.............................
IOError: [Errno 13] Permission denied: u'/config/flexget.log'
Traceback (most recent call last):
```

The container dies after a number attempts to write.

Here's the contents of the config directory:

```
$ ls -altr /shared/flexget
-rwx------  1 ken  ken      262 Aug 14 13:52 config.yml
----------  1  911  8378      0 Aug 14 13:54 .password-lock
-rwx------  1 root root  253952 Aug 14 13:55 db-config.sqlite
-rwx------  1 root root    6669 Aug 14 13:55 flexget.log
```

**Comment by mastermindg** [comment]
I can get around the problem by waiting for the files to be created, stopping the container, fixing the perms and then restarting the container. I've scripted this for now, however it's definitely an issue that should be resolved.

**Comment by cpoppema** [comment]
Thanks for bringing this up! I fiddled around a bit and it seems there is indeed an issue regarding (nfs) mounts. Across machines, `root` seems to have not as much access as a "local" `root`, depending on the folder permissions. For example:

Setting up a share on `server`.
```
server $ su
server # mkdir /local/tmp/test-nfs-share
server # chown -R share: /local/tmp/test-nfs-share
server # echo "/local/tmp/test-nfs-share/   192.168.1.0/24(rw,nohide,insecure,no_subtree_check,async)" >> /etc/exports
server # exportfs -a
server # exit
server $ exit
```

Mounting it on `pc`.
```
pc $ su
pc # mkdir /mnt/test-nfs-mount
pc # mount -t nfs server:/local/tmp/test-nfs-share /mnt/test-nfs-mount
```

Now, to "show" difference between root access level. First touch a file on localhost, `server`.
```
server # cd /local/tmp/test-nfs-share/
server # touch .password-lock
server # echo $?
0
server # rm .password-lock
```

Next, do the same on the mount.

```
pc # cd /mnt/test-nfs-mount
pc # touch .password-lock && echo $?
touch: cannot touch '.password-lock': Permission denied
```

And that's the issue.

It looks like I can work around it by setting the uid/gid for the docker user simply at an earlier time and also running `touch` as that user, instead of trying to do some actions as root and then changing ownership. To remedy the other files being created as root I will also run the command setting the web ui password as the docker user to prevent creating files (ie. when running it for the first time) owned by root.

**Comment by cpoppema** [comment]
There is a new image available, please let me know if that fixes it for you. You can run `
docker pull cpoppema/docker-flexget` before running `start.sh` again.
