### ISSUE TITLE
Time Zone / clock sync settings?

### ISSUE THREAD

**Issue by bagobones** [cpoppema/docker-flexget#16]
Any chance the TZ timezone variable could be added to this image? I am tried of doing the GMT / daylight savings time math on my flexget logs, I would love for it to log in my proper time zone.

**Comment by cpoppema** [comment]
Thanks for reporting this, it is already a built-in variable supported by the base image. But.. after trying and looking at it myself, it seems like it no longer works out-of-the-box since the latest update of [phusion/baseimage](https://github.com/phusion/baseimage-docker/issues/415):

```
 $    docker run -e TZ=CET --rm phusion/baseimage:0.9.21 date
Fri Oct 13 21:03:08 CEST 2017
```

```
 $    docker run -e TZ=CET --rm phusion/baseimage:0.9.22 date
Fri Oct 13 19:03:14 CET 2017
```

Apparently the package that supplies timezone data is no longer installed by default since that update. I've added `tzdata` to the list of installed packages in my Dockerfile.

As far as configuration goes, you can pass anything that exists in `/usr/share/zoneinfo`, for example:

```
TZ=/usr/share/zoneinfo/Europe/Amsterdam 
TZ=CET
TZ=Pacific/Easter
```

Just now I pushed an update, just have to wait until it is done building, and then you can run `docker pull cpoppema/docker-flexget`. See build progress here: https://hub.docker.com/r/cpoppema/docker-flexget/builds/
