### ISSUE TITLE
Overall Image size is very large

### ISSUE THREAD

**Issue by bagobones** [cpoppema/docker-flexget#17]
I am not sure if it is the additional dependencies for Transmission/Deluge that drive up the size of this particular image but it is substantially large vs other Flexget docker images.

This does not create any direct problems but this image is around 500mb which is almost double that of something like plexpy, or even the linuxserver transmission image which is only 39mb.

I wonder if this image could be more lean.

**Comment by cpoppema** [comment]
Thanks for reporting in @bagobones. The image size itself is using a full Ubuntu Xenial base image and the packages that are installed from the Ubuntu repository indeed take up additional space. When building this image you'll see something like for the `apt-get install` command: `
After this operation, 259 MB of additional disk space will be used.
`

Nevertheless, I can see other images have moved towards different base images since I first created this flexget image, and those have come a long way (alpine back then did not fully work). Personally I simply never need to save disk space, so I'm glad you pointed this out and I will investigate what options there are :).

**Comment by bagobones** [comment]
Its not just a space issue, the extra packages can cause extra memory and CPU use as well which when multiplied across a larger number of containers on a low resource host device like a NAS can add up.

It would be great if it was slimmed down a bit.. Not a deal breaker just something I noticed again when updating the image for the timezone fix you put in.

**Comment by cpoppema** [comment]
I've updated to a baseimage that's also used by linuxserver.io these days. Besides the few kilobytes of files you can find in this repository, it does not take up additional space. Everything (flexget + plugin dependencies) is installed on first start.

**Comment by bagobones** [comment]
575MB down to 133MB  is much better for the container and it looks like it is using about 100MB less RAM..

Thanks.
