### ISSUE TITLE
Deluge plugin not working

### ISSUE THREAD

**Issue by murbancic** [cpoppema/docker-flexget#19]
Changing the torrent plugin to deluge and installing, running a config file returns:

> 2017-11-12 03:31 CRITICAL task          tv         Plugin `deluge` cannot be used because dependency `deluge` is missing.
2017-11-12 03:31 WARNING  task          tv         Aborting task (plugin: deluge)

**Comment by cpoppema** [comment]
Thanks for bringing this to my attention @murbancic.

After taking a look I it seems the installation of the deluge package is failing due to unmet dependencies in a dependecy of deluge.

```
$ apk add --no-cache --repository http://nl.alpinelinux.org/alpine/edge/testing deluge
...
ERROR: unsatisfiable constraints:
  so:libcrypto.so.42 (missing):
    required by:
                 libtorrent-rasterbar-1.0.11-r4[so:libcrypto.so.42]
                 libtorrent-rasterbar-1.0.11-r4[so:libcrypto.so.42]
  so:libssl.so.44 (missing):
    required by:
                 libtorrent-rasterbar-1.0.11-r4[so:libssl.so.44]
                 libtorrent-rasterbar-1.0.11-r4[so:libssl.so.44]
```

Apparently, libtorrent-rasterbar just pushed out a new version 2/3 days ago, breaking the chain of dependencies. libtorrent-rasterbar depends on libressl instead of openssl which I initially installed. Though similar, the alpine package for libressl was more recently updated than the one for openssl.

A new image should be available shortly.
