### ISSUE TITLE
urllib3 or chardet doesn't match a supported version

### ISSUE THREAD

**Issue by shadycuz** [cpoppema/docker-flexget#21]
I start the container `root@compute02:~# docker run --name flexget -e WEB_PASSWD=test -e TORRENT_PLUGIN=deluge cpoppema/docker-flexget`, the update process is long but it finnaly completes.
```
[cont-init.d] 22-update-deluge: exited 0.
[cont-init.d] 30-set-web-passwd: executing...
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 24, in main
    manager = Manager(args)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 158, in __init__
    self.find_config(create=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 535, in find_config
    raise IOError('Config `%s` does not appear to be a file.' % config)
IOError: Config `/config/config.yml` does not appear to be a file.
[cont-init.d] 30-set-web-passwd: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 24, in main
    manager = Manager(args)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 158, in __init__
    self.find_config(create=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 535, in find_config
    raise IOError('Config `%s` does not appear to be a file.' % config)
IOError: Config `/config/config.yml` does not appear to be a file.
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/flexget/__init__.py", line 24, in main
    manager = Manager(args)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 158, in __init__
    self.find_config(create=False)
  File "/usr/lib/python2.7/site-packages/flexget/manager.py", line 535, in find_config
    raise IOError('Config `%s` does not appear to be a file.' % config)
IOError: Config `/config/config.yml` does not appear to be a file.
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
```

Then it flips out about dependencies and config files. I'm guessing there is no default config file? Maybe we should add one in case a person doesn't have one, or they just want to test the container?

**Comment by shadycuz** [comment]
Passing in a config file worked `time docker run --name flexget -e WEB_PASSWD=test -e TORRENT_PLUGIN=deluge -v ${PWD}:/config cpoppema/docker-flexget`, still get the warning but it is only a warning, `/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)`. 

Is it normal for it to complain about missing password? ```2017-12-14 14:55 WARNING  web_server                    No password set for web server, create one by using `flexget web passwd <password>` ```

and it takes nearly 5 mins for it to start `real    4m15.885s`

**Comment by cpoppema** [comment]
Hello @shadycuz, thanks for giving it a try!

At this time, there isn't a working config.yml that works as an example. I felt it was best to show an example in the README since I believe _most_ people are coming from an existing setup and are moving it to docker. I will re-evaluate this, so thank you for bringing this up.

I can't do much about the warnings you see. Whatever you see is coming from a fresh install of flexget and either transmission or deluge dependencies. This docker image does not intent to prevent/solve these warnings _if_ they are the result of a clean install. If someone can tell me they don't see them when doing a clean install themselves I'll gladly take some time investigating.

About the warning by the web_server plugin: it took me a while to figure out. I overlooked this log message at first, but it is pretty clear:

```
[cont-init.d] 30-set-web-passwd: executing...
...
Password 'test' is not strong enough. This is a top-100 common password. Suggestions: Add another word or two. Uncommon words are better.
...
[cont-init.d] 30-set-web-passwd: exited 0.
```

Don't forget to remove the `.password-lock` file in the config directory if you change the password by changing WEB_PASSWD. (You can of course always run the suggested command to put the new password in your flexget database file).

In the last major change for this docker image I changed the base image. It now runs on alpine instead of Ubuntu. With this change, I also mimicked other images that use the same base image. This means that when starting the container for the first time, the main application that runs inside is _installed_ instead of just checking for updates. As a result of this change, base images won't come with an old version on some application, but just the scripts to install/update it. The deluge plugin also has a lot more dependencies compared to the transmission plugin, so that also adds up. E.g. the difference on my machine between deluge/transmission:

Adding `bash -c date` will show the timestamp inside the container when all install/setup scripts are done before starting the shutdown scripts. The time you see reported by `time` also include the time it takes to run these shutdown scripts (about 5 seconds).

```
$ date && time docker run --rm --name flexget-transmission -e WEB_PASSWD=test -e TORRENT_PLUGIN=transmission -v ${PWD}:/config cpoppema/docker-flexget bash -c date
real    0m37.471s
user    0m0.028s
sys     0m0.008s
```

```
$ date && time docker run --rm --name flexget-deluge -e WEB_PASSWD=test -e TORRENT_PLUGIN=deluge -v ${PWD}:/config cpoppema/docker-flexget bash -c date
real    0m50.346s
user    0m0.032s
sys     0m0.012s
```

If you have any more questions, let me know! :)

**Comment by shadycuz** [comment]
Hey thanks for the lengthy explanation! Makes sense to me. I've never used S6 overlay so it's been challenging for me to get going.

I don't see the msg that password test is not strong enough where can I find that?
EDIT: Awwww it's the log level? I have mine set to info

I don't really like the "self updating container" or that the software installs on container start, seems to go against the point of containers `¯\_(ツ)_/¯` ? But I don't want to to create and maintain my own image. I would rather collab =). What if we made the container so it installed flexget on container build with a demo config (only web_gui enabled?). Then you can signal with an ENV variable that you want to update flexget on start with `AUTO_UPDATE = true`, and of course, we could handle the torrent plugin at container start for people who are not going to build their own private images. I could do most of this work if you are interested.

I'm having one last problem, but it's not an issue with your image, it's most likely an issue with flexget. 

```
[cont-init.d] 30-set-web-passwd: executing... 
/usr/lib/python2.7/site-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.22) or chardet (2.3.0) doesn't match a supported version!
  RequestsDependencyWarning)
Could not instantiate manager: Config `/config/config.yml` does not appear to be a file.
[cont-init.d] 30-set-web-passwd: exited 1.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
```

It doesn't like my config file.

```
root@automated-media-86b6d6f96-zmctv:/$ ls -la /config/
total 4
drwxrwxrwt  3 abc  abc   100 Dec 15 13:21 .
drwxr-xr-x 54 root root 4096 Dec 15 13:20 ..
drwxr-xr-x  2 root root   60 Dec 15 13:21 ..129812_15_12_13_21_23.948212188
lrwxrwxrwx  1 root root   33 Dec 15 13:21 ..data -> ..129812_15_12_13_21_23.948212188
lrwxrwxrwx  1 root root   17 Dec 15 13:17 config.yml -> ..data/config.yml
```

I'm running on kubernetes so I might just bake my config into the container instead of mounting it as a volume.

**Comment by shadycuz** [comment]
I looked for what an acceptable password would be but they are using some kinda tool and I don't see documentation from flexget on it or the tool provider, seems cool though. https://github.com/dropbox/zxcvbn

It appears it's just a warning.
```
@with_session
def change_password(username='flexget', password='', session=None):
    check = zxcvbn.zxcvbn(password, user_inputs=[username])
    if check['score'] < 3:
        warning = check['feedback']['warning']
        suggestions = ' '.join(check['feedback']['suggestions'])
        message = 'Password \'{}\' is not strong enough. '.format(password)
        if warning:
            message += warning + ' '
        if suggestions:
            message += 'Suggestions: {}'.format(suggestions)
        raise WeakPassword(message)

    user = get_user(username=username, session=session)
    user.password = str(generate_password_hash(password))
    session.commit()
```

Wish they didn't echo the plain text password into the log ;) , I wont use TEST on the web! It was for testing ;)

**Comment by shadycuz** [comment]
Correction, It does not set the password.

**Comment by cpoppema** [comment]
> I don't really like the "self updating container" or that the software installs on container start, seems to go against the point of containers

I can understand that as a user you'd want it to "just work". I believe there are (at least) two groups of maintainers of docker images out there.
One is the owner/author of the actual software. It makes sense to publish a new (versioned) container for every release.
Second is "the community", people that use and love an application and put in the effort to make it work in docker and/or tailor it to their preferences and put it out there for others to use. In this case having an auto-update mechanism means that you can provide the latest version of an application without having to monitor application releases to prevent the docker image from being outdated. Continuing on this point, not so long ago I did used to have some version of Flexget installed, but still with the auto-update in place, this only made the image larger while needing to upgrade on first start anyway after a new version was released. For that reason it only made sense to me to no longer add a snapshot installation at the time of the image being built, but to install on first start as well.

As long as the installation works on first start, I believe that installation/updating when starting the container has accomplished for it to "just work". It might take a little longer compared to only updating, but it saves a lot in image size as well. So, in my eyes, it does not defeat the purpose of containers. There's still a lot more to it.. You don't have to worry about how to install an application or its dependencies and it still provides isolation between containers and the host OS.

> It doesn't like my config file.

What do you see inside the container ? I'm not sure if I'm seeing this OK, but if data/config.yml are symlinks and point to a location outside your current working directory, that's a problem for docker. It can show you the symlink inside the container, but it won't find its target. If you want to keep data/config.yml on the location it is now, one workaround is to use hardlink instead of symlink or to [mount the directory](https://superuser.com/a/842690).

**Comment by kariudo** [comment]
Though @shadycuz seems to have some other issues here. I would like to point out to anyone else who has some annoyance with the warning that this issue is titled after, it can be fixed by just running `pip install --upgrade chardet` to upgrade the package after setup for now, its a dependency of the _request_ package which is what complains with the warning.

**Comment by shadycuz** [comment]
So the takeaway is you need a long and complicated password and the warning is only a warning. Been using the container for a few weeks now. It's been great. See the above comment on how to fix.

**Comment by Sphinxs** [comment]
Some update ?

```
➜  markov git:(master) ✗ pip freeze | grep urllib3
urllib3==1.23
➜  markov git:(master) ✗ python3 enem.py
/usr/lib/python3/dist-packages/requests/__init__.py:80: RequestsDependencyWarning: urllib3 (1.23) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)
➜  markov git:(master) ✗
```
