### ISSUE TITLE
Plugin `convert_magnet` cannot be used because dependency `libtorrent` is missing.

### ISSUE THREAD

**Issue by ghost** [cpoppema/docker-flexget#30]
Hi,
I'd like to use the `convert_magnet` plugin when "TORRENT_PLUGIN=transmission".
Could you please install the dependency `libtorrent` in your script?

Thanks

**Comment by cpoppema** [comment]
Hi @joelliang thanks for your suggestion. I updated the image to always install libtorrent - this was easy since I already figured out all the dependencies for when you'd use the deluge plugin!

While testing I also regularly saw conversions fail due to it taking longer than the default timeout of 30 seconds. If this also happens to you, make sure to increase the timeout in your config, see https://flexget.com/Plugins/convert_magnet.

**Comment by ghost** [comment]
Thanks for your quick response. I just found out that the transmissionrpc plugin can support magnet link directly.
