### ISSUE TITLE
Consider making container flexget official

### ISSUE THREAD

**Issue by ssbarnea** [cpoppema/docker-flexget#39]
It seems that your flexget container is the most popular flexget one and I wonder if you would not be interested in helping achieving https://github.com/Flexget/Flexget/issues/2359

**Comment by cpoppema** [comment]
Sorry for taking my time to get back to you @ssbarnea . In https://github.com/cpoppema/docker-flexget/issues/21 I happen to mention my outlook on the types of container images I think can exist:

> One is the owner/author of the actual software. It makes sense to publish a new (versioned) container for every release.

> Second is "the community", people that use and love an application and put in the effort to make it work in docker and/or tailor it to their preferences and put it out there for others to use. In this case having an auto-update mechanism means that you can provide the latest version of an application without having to monitor application releases to prevent the docker image from being outdated.

This container falls in the second category. If there was ever an official Flexget container image I would very much like to see a fully automated build system with versioned releases. These would have each a specific version of Flexget installed - replacing the auto-update mechanism. This seems necessary to provide stable releases looking at my own[1]. The other matter is support for Flexget plugins. I've not looked at how many plugins there actually are, but they can have dependencies of their own that also need to be maintained or that can break during installation (e.g. deluge). Right now I can assume a few plugins work, but usually have no way of testing them (easily).

[1] Since I've switched to alpine there have been a number of installation failures due to breaking dependencies (thankfully people do report this on github here) and I'd either had to lookup what has changed and add/remove dependencies etc. or all I could do was sit and to wait hours or sometimes days until broken dependencies were resolved to be able to rebuild a new image.

I'm curious to hear what you think

**Comment by evlo** [comment]
Ehh, just wondering what is difference between python in container and `bin/pip3 install --upgrade pip`
`bin/pip3 install --upgrade flexget` in system.

BTW I don't mind autoupdate, I would even like it if there was option to run autoupdate on schedule by the container.

**Comment by cpoppema** [comment]
Hello @evlo, I'm not sure what you mean ? If it's not related to this topic, consider making a new issue. Thank you.
