### ISSUE TITLE
Telegram notifier needs `python-telegram-bot` python pkg

### ISSUE THREAD

**Issue by paolobasso99** [cpoppema/docker-flexget#52]
Hi,
I'd like to use the Telegram notifier but it requires an additional python package as described in the [plugin page](https://flexget.com/Plugins/Notifiers/telegram); is there any chance to include this package in this docker image?
Maybe the package could be installed only if an environment variable is set if you don't want to include it to every container.

**Comment by cpoppema** [comment]
Hi @paolobasso99, thank you for trying to make this image even better.

I will look into it, probably this week. I usually try to find out what the dependencies are and then decide if it is something that can be included always or only conditionally. I think ideally I would try to detect plugins from the config.yml and installs them accordingly, but that requires a little bit more work.

The plugin seems to only rely on that package (no system dependencies), so that should speed things up :)

**Comment by cpoppema** [comment]
I added it to the list of other plugins that are installed by default. I really like my idea to dynamically install plugins based on the config.yml but that will have to wait. Notifications to telegram should work for now!

**Comment by paolobasso99** [comment]
Thank you!
I like the idea to install plugins dynamically too!
